### ISSUE TITLE
Error when using example code

### ISSUE THREAD

**Issue by hsdhillon** [voycey/salesforce-datasource-cakephp-3.x#4]
Hi,

I am trying this plugin with CakePHP 3.x but I am stuck at this error while using the example code you have  in readme. Below is the error message I am getting

```
Error: Uncaught Error: Using $this when not in object context in /home/jj/testproject/vendor/voycey/cakephp-salesforce/src/Database/SalesforceQuery.php:54 Stack trace: #0 /home/jj/testproject/vendor/voycey/cakephp-salesforce/src/ORM/SalesforceQuery.php(63): Salesforce\Database\SalesforceQuery::sql(NULL, Object(Salesforce\ORM\SalesforceQuery)) #1 /home/jj/testproject/vendor/voycey/cakephp-salesforce/src/Database/Statement/SalesforceStatement.php(37): Salesforce\ORM\SalesforceQuery->sql() #2 /home/jj/testproject/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php(174): Salesforce\Database\Statement\SalesforceStatement->execute(NULL) #3 /home/jj/testproject/vendor/cakephp/cakephp/src/Database/Log/LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL) #4 /home/jj/testproject/vendor/voycey/cakephp-salesforce/src/Database/SalesforceConnection.php(64): Cake\Database 
File /home/jj/testproject/vendor/voycey/cakephp-salesforce/src/Database/SalesforceQuery.php 
Line: 54
```
Any help is much appreciated.

Thanks for developing this package.

**Comment by Zuluru** [comment]
I was able to work around this by replacing usages of $this in that function with $incoming. It seems that this was built for an earlier version of CakePHP 3, and some changes in Cake have caused little errors like this. I'm working on fixing these in a fork, if anyone else has done similar changes I'd be interested to hear from you!
